export interface Localization {
    locale: string,
    placeholderText: string,
    dateFormatString: string,
    wordOrTranslated: string,
    dateFormatOptions: string[],
    generalDateFieldError: string,
    keyboardNavInstructions: string,
    buttonLabelChoose: string,
    buttonLabelChange: string,
    buttonLabelPreviousMonth: string,
    buttonLabelPreviousYear: string,
    buttonLabelNextMonth: string,
    buttonLabelNextYear: string,
    dayNames: string[],
    dayNamesShort: string[],
    monthNames: string[],
    monthNamesForMessage: string[],    
    selectFocusedButtonLabel: string,
    cancelButtonLabel: string
}